default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_P8_PATH"],
      in_house: false
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "ios/OkHiApp.xcodeproj"
    )

    build_app(
      workspace: "ios/OkHiApp.xcworkspace",
      scheme: "OkHiApp",
      export_method: "app-store",
      export_team_id: "ZV9VNGTKRL",
      configuration: "Release",
      clean: true,
      output_directory: "./build",
      output_name: "OkHiApp.ipa",
      xcargs: "-allowProvisioningUpdates -authenticationKeyPath '#{ENV["ASC_KEY_P8_PATH"]}' -authenticationKeyID '#{ENV["ASC_KEY_ID"]}' -authenticationKeyIssuerID '#{ENV["ASC_ISSUER_ID"]}'"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end
end

platform :android do
  desc "Build signed AAB and upload to Play Store Internal Testing"
  lane :internal do
    require 'base64'

    # Decode keystore from base64 secret and write to a temp file
    keystore_path = "/tmp/release.keystore"
    File.write(keystore_path, Base64.decode64(ENV["ANDROID_KEYSTORE_BASE64"]))

    # Always-increasing version code: minutes since Unix epoch (~29M in Feb 2026)
    version_code = (Time.now.to_i / 60).to_i

    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "android/",
      properties: {
        "android.injected.signing.store.file" => keystore_path,
        "android.injected.signing.store.password" => ENV["ANDROID_STORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"],
        "versionCode" => version_code.to_s,
      }
    )

    upload_to_play_store(
      track: "internal",
      release_status: "completed",
      json_key_data: ENV["PLAY_STORE_JSON_KEY"],
      aab: "android/app/build/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  ensure
    File.delete(keystore_path) if File.exist?(keystore_path)
  end
end
